/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ja') | ('en' | 'ja')[];
  globals: {
    navbar: Navbar;
    footer: Footer;
  };
  globalsSelect: {
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en' | 'ja';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Internal page title (e.g., Home Page)
   */
  title: string;
  /**
   * URL slug (e.g., "home" or "pricing")
   */
  slug: string;
  layout: (
    | {
        /**
         * Accepts HTML like <br> and <blue>
         */
        heading?: string | null;
        subheading?: string | null;
        heroCTA?: string | null;
        heroSecondaryCTA?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        mainTitle?: string | null;
        reasonText?: string | null;
        whyChooseUs?: string | null;
        reasons?:
          | {
              title?: string | null;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'whyChooseUs';
      }
    | {
        title?: string | null;
        introText?: string | null;
        benefitsList?:
          | {
              benefitWord?: string | null;
              id?: string | null;
            }[]
          | null;
        contentList?:
          | {
              listItem?: string | null;
              id?: string | null;
            }[]
          | null;
        scheduleLabels?: {
          classSchedule?: string | null;
          morningTime?: string | null;
          afternoonTime?: string | null;
          eveningTime?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'benefits';
      }
    | {
        badge?: string | null;
        title?: string | null;
        lecturer?: {
          name?: string | null;
          role?: string | null;
          bio?: string | null;
          universityName?: string | null;
          universityRole?: string | null;
        };
        cta?: {
          text?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'lecturerIntroduction';
      }
    | {
        badge?: string | null;
        title?: string | null;
        publications?:
          | {
              name: string;
              description?: string | null;
              articles?:
                | {
                    title?: string | null;
                    url: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pressSection';
      }
    | {
        title?: string | null;
        subtitle?: string | null;
        labels?: {
          monthly?: string | null;
          biannual?: string | null;
          annual?: string | null;
          taxIncl?: string | null;
          noCard?: string | null;
          billedMonthly?: string | null;
          billedBiannual?: string | null;
          billedAnnual?: string | null;
        };
        freeTrial?: {
          name?: string | null;
          price?: string | null;
          buttonText?: string | null;
          features?:
            | {
                category?: string | null;
                text?: string | null;
                isIncluded?: boolean | null;
                subtext?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        unlimited?: {
          name?: string | null;
          buttonText?: string | null;
          cycles?: {
            monthly?: {
              price?: string | null;
              link?: string | null;
              features?:
                | {
                    category?: string | null;
                    text?: string | null;
                    isIncluded?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
            };
            biannual?: {
              price?: string | null;
              link?: string | null;
              features?:
                | {
                    category?: string | null;
                    text?: string | null;
                    isIncluded?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
            };
            annual?: {
              price?: string | null;
              link?: string | null;
              features?:
                | {
                    category?: string | null;
                    text?: string | null;
                    isIncluded?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
            };
          };
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricing';
      }
    | {
        title?: string | null;
        feature1?: string | null;
        feature2?: string | null;
        cta?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'freeTrialSection';
      }
    | {
        badge?: string | null;
        title?: string | null;
        description?: string | null;
        steps?:
          | {
              title?: string | null;
              subtitle?: string | null;
              description?: string | null;
              icon?: ('users' | 'monitor' | 'compass' | 'messages') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'learningCycle';
      }
    | {
        title?: string | null;
        subtitle?: string | null;
        steps?:
          | {
              day?: string | null;
              title?: string | null;
              description?: string | null;
              icon?: ('zap' | 'userCheck' | 'globe' | 'shieldCheck') | null;
              id?: string | null;
            }[]
          | null;
        ctaTitle?: string | null;
        ctaDescription?: string | null;
        ctaButtonText?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'roadmap';
      }
    | {
        title?: string | null;
        team?:
          | {
              name: string;
              role?: string | null;
              /**
               * The filename of the static image (e.g., sarah-birchley.jpg)
               */
              staticImageKey?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'instructorsSection';
      }
    | {
        badge?: string | null;
        title?: string | null;
        items?:
          | {
              quote?: string | null;
              authorName?: string | null;
              authorRole?: string | null;
              stars?: number | null;
              /**
               * The single letter shown in the colored box (e.g., S)
               */
              initial?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        badge?: string | null;
        title?: string | null;
        description?: string | null;
        levels?:
          | {
              levelLabel: string;
              levelTitle?: string | null;
              levelDescription?: string | null;
              programs?:
                | {
                    title?: string | null;
                    link?: string | null;
                    /**
                     * e.g. /img/globals/C01.webp
                     */
                    imagePath?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'programs';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              heroCTA?: T;
              heroSecondaryCTA?: T;
              id?: T;
              blockName?: T;
            };
        whyChooseUs?:
          | T
          | {
              mainTitle?: T;
              reasonText?: T;
              whyChooseUs?: T;
              reasons?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        benefits?:
          | T
          | {
              title?: T;
              introText?: T;
              benefitsList?:
                | T
                | {
                    benefitWord?: T;
                    id?: T;
                  };
              contentList?:
                | T
                | {
                    listItem?: T;
                    id?: T;
                  };
              scheduleLabels?:
                | T
                | {
                    classSchedule?: T;
                    morningTime?: T;
                    afternoonTime?: T;
                    eveningTime?: T;
                  };
              id?: T;
              blockName?: T;
            };
        lecturerIntroduction?:
          | T
          | {
              badge?: T;
              title?: T;
              lecturer?:
                | T
                | {
                    name?: T;
                    role?: T;
                    bio?: T;
                    universityName?: T;
                    universityRole?: T;
                  };
              cta?:
                | T
                | {
                    text?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pressSection?:
          | T
          | {
              badge?: T;
              title?: T;
              publications?:
                | T
                | {
                    name?: T;
                    description?: T;
                    articles?:
                      | T
                      | {
                          title?: T;
                          url?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              title?: T;
              subtitle?: T;
              labels?:
                | T
                | {
                    monthly?: T;
                    biannual?: T;
                    annual?: T;
                    taxIncl?: T;
                    noCard?: T;
                    billedMonthly?: T;
                    billedBiannual?: T;
                    billedAnnual?: T;
                  };
              freeTrial?:
                | T
                | {
                    name?: T;
                    price?: T;
                    buttonText?: T;
                    features?:
                      | T
                      | {
                          category?: T;
                          text?: T;
                          isIncluded?: T;
                          subtext?: T;
                          id?: T;
                        };
                  };
              unlimited?:
                | T
                | {
                    name?: T;
                    buttonText?: T;
                    cycles?:
                      | T
                      | {
                          monthly?:
                            | T
                            | {
                                price?: T;
                                link?: T;
                                features?:
                                  | T
                                  | {
                                      category?: T;
                                      text?: T;
                                      isIncluded?: T;
                                      id?: T;
                                    };
                              };
                          biannual?:
                            | T
                            | {
                                price?: T;
                                link?: T;
                                features?:
                                  | T
                                  | {
                                      category?: T;
                                      text?: T;
                                      isIncluded?: T;
                                      id?: T;
                                    };
                              };
                          annual?:
                            | T
                            | {
                                price?: T;
                                link?: T;
                                features?:
                                  | T
                                  | {
                                      category?: T;
                                      text?: T;
                                      isIncluded?: T;
                                      id?: T;
                                    };
                              };
                        };
                  };
              id?: T;
              blockName?: T;
            };
        freeTrialSection?:
          | T
          | {
              title?: T;
              feature1?: T;
              feature2?: T;
              cta?: T;
              id?: T;
              blockName?: T;
            };
        learningCycle?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
              steps?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        roadmap?:
          | T
          | {
              title?: T;
              subtitle?: T;
              steps?:
                | T
                | {
                    day?: T;
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              ctaTitle?: T;
              ctaDescription?: T;
              ctaButtonText?: T;
              id?: T;
              blockName?: T;
            };
        instructorsSection?:
          | T
          | {
              title?: T;
              team?:
                | T
                | {
                    name?: T;
                    role?: T;
                    staticImageKey?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              badge?: T;
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorRole?: T;
                    stars?: T;
                    initial?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        programs?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
              levels?:
                | T
                | {
                    levelLabel?: T;
                    levelTitle?: T;
                    levelDescription?: T;
                    programs?:
                      | T
                      | {
                          title?: T;
                          link?: T;
                          imagePath?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: number;
  links?: {
    why?: string | null;
    programs?: string | null;
    pricing?: string | null;
    instructors?: string | null;
    freeTrial?: string | null;
    login?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  companyName?: string | null;
  officeAddress?: string | null;
  contactEmail?: string | null;
  phoneNumber?: string | null;
  labels?: {
    company?: string | null;
    office?: string | null;
    contact?: string | null;
    links?: string | null;
    contactUs?: string | null;
    privacyPolicy?: string | null;
    companyProfile?: string | null;
    copyright?: string | null;
    email?: string | null;
    call?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  links?:
    | T
    | {
        why?: T;
        programs?: T;
        pricing?: T;
        instructors?: T;
        freeTrial?: T;
        login?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  companyName?: T;
  officeAddress?: T;
  contactEmail?: T;
  phoneNumber?: T;
  labels?:
    | T
    | {
        company?: T;
        office?: T;
        contact?: T;
        links?: T;
        contactUs?: T;
        privacyPolicy?: T;
        companyProfile?: T;
        copyright?: T;
        email?: T;
        call?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}